# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qtdesigner.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(791, 577)
        MainWindow.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 178, 102, 255), stop:0.55 rgba(235, 148, 61, 255), stop:0.98 rgba(0, 0, 0, 255), stop:1 rgba(0, 0, 0, 0));")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(580, 120, 111, 23))
        self.pushButton.setStyleSheet("background-color: rgb(255, 222, 144);")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../Desktop/тестовое задание/medium_f0d7b9975fe120cf5d14799c11606a99.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(20, 20))
        self.pushButton.setObjectName("pushButton")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(110, 150, 581, 421))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableView = QtWidgets.QTableView(self.layoutWidget)
        self.tableView.setStyleSheet("background-color: rgb(207, 207, 207);")
        self.tableView.setObjectName("tableView")
        self.verticalLayout.addWidget(self.tableView)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.BlockB = QtWidgets.QPushButton(self.layoutWidget)
        self.BlockB.setStyleSheet("background-color: rgb(255, 222, 144);")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../../Desktop/тестовое задание/free-icon-cloud-database-2637294.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BlockB.setIcon(icon1)
        self.BlockB.setIconSize(QtCore.QSize(18, 18))
        self.BlockB.setObjectName("BlockB")
        self.horizontalLayout.addWidget(self.BlockB)
        self.PortB = QtWidgets.QPushButton(self.layoutWidget)
        self.PortB.setStyleSheet("background-color: rgb(255, 222, 144);")
        self.PortB.setIcon(icon1)
        self.PortB.setIconSize(QtCore.QSize(18, 18))
        self.PortB.setObjectName("PortB")
        self.horizontalLayout.addWidget(self.PortB)
        self.BoardB = QtWidgets.QPushButton(self.layoutWidget)
        self.BoardB.setStyleSheet("background-color: rgb(255, 222, 144);")
        self.BoardB.setIcon(icon1)
        self.BoardB.setIconSize(QtCore.QSize(18, 18))
        self.BoardB.setObjectName("BoardB")
        self.horizontalLayout.addWidget(self.BoardB)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(310, 69, 201, 53))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.ConnectionStatus = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ConnectionStatus.setFont(font)
        self.ConnectionStatus.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.ConnectionStatus.setObjectName("ConnectionStatus")
        self.gridLayout.addWidget(self.ConnectionStatus, 0, 0, 1, 2)
        self.begin = QtWidgets.QPushButton(self.layoutWidget1)
        self.begin.setStyleSheet("background-color: rgb(204, 204, 204);")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../../Desktop/тестовое задание/free-icon-plug-and-play-6878161.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.begin.setIcon(icon2)
        self.begin.setIconSize(QtCore.QSize(18, 18))
        self.begin.setObjectName("begin")
        self.gridLayout.addWidget(self.begin, 1, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MorionQTApp"))
        self.pushButton.setText(_translate("MainWindow", "Загрузить Базу"))
        self.BlockB.setText(_translate("MainWindow", "Блоки"))
        self.PortB.setText(_translate("MainWindow", "Платы"))
        self.BoardB.setText(_translate("MainWindow", "Порты"))
        self.ConnectionStatus.setText(_translate("MainWindow", "     Connection status:"))
        self.begin.setText(_translate("MainWindow", "Начать сеанс"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
